<?php

class CitiesTableSeeder extends Seeder{

	public function run()
	{
		$table = 'cities';

		DB::table($table)->truncate();

		$data = array(
			0 => array(
				'country_id'	=> 1,
				'name' 			=> 'Jakarta',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			1 => array(
				'country_id'	=> 1,
				'name' 			=> 'Surabaya',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			2 => array(
				'country_id'	=> 1,
				'name' 			=> 'Medan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			3 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bandung',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			4 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bekasi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			5 => array(
				'country_id'	=> 1,
				'name' 			=> 'Palembang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			6 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tangerang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			7 => array(
				'country_id'	=> 1,
				'name' 			=> 'Makassar',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			8 => array(
				'country_id'	=> 1,
				'name' 			=> 'Semarang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			9 => array(
				'country_id'	=> 1,
				'name' 			=> 'Depok',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			10 => array(
				'country_id'	=> 1,
				'name' 			=> 'Mamuju',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			11 => array(
				'country_id'	=> 1,
				'name' 			=> 'Padang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			12 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tanjungkarang-Telukbetung',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			13 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bogor',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			14 => array(
				'country_id'	=> 1,
				'name' 			=> 'Malang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			15 => array(
				'country_id'	=> 1,
				'name' 			=> 'Yogyakarta',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			16 => array(
				'country_id'	=> 1,
				'name' 			=> 'Situbondo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			17 => array(
				'country_id'	=> 1,
				'name' 			=> 'Banjarmasin',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			18 => array(
				'country_id'	=> 1,
				'name' 			=> 'Solo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			19 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cimahi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			20 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pontianak',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			21 => array(
				'country_id'	=> 1,
				'name' 			=> 'Manado',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			22 => array(
				'country_id'	=> 1,
				'name' 			=> 'Balikpapan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			23 => array(
				'country_id'	=> 1,
				'name' 			=> 'Jambi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			24 => array(
				'country_id'	=> 1,
				'name' 			=> 'Denpasar',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			25 => array(
				'country_id'	=> 1,
				'name' 			=> 'Ambon',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			26 => array(
				'country_id'	=> 1,
				'name' 			=> 'Samarinda',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			27 => array(
				'country_id'	=> 1,
				'name' 			=> 'Mataram',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			28 => array(
				'country_id'	=> 1,
				'name' 			=> 'Percut',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			29 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bengkulu',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			30 => array(
				'country_id'	=> 1,
				'name' 			=> 'Jember',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			31 => array(
				'country_id'	=> 1,
				'name' 			=> 'Palu',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			32 => array(
				'country_id'	=> 1,
				'name' 			=> 'Kupang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			33 => array(
				'country_id'	=> 1,
				'name' 			=> 'Sukabumi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			34 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tasikmalaya',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			35 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pekalongan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			36 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cirebon',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			37 => array(
				'country_id'	=> 1,
				'name' 			=> 'Banda Aceh',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			38 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tegal',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			39 => array(
				'country_id'	=> 1,
				'name' 			=> 'Kediri',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			40 => array(
				'country_id'	=> 1,
				'name' 			=> 'Binjai',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			41 => array(
				'country_id'	=> 1,
				'name' 			=> 'Purwokerto',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			42 => array(
				'country_id'	=> 1,
				'name' 			=> 'Purwakarta',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			43 => array(
				'country_id'	=> 1,
				'name' 			=> 'Loa Janan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			44 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pematangsiantar',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			45 => array(
				'country_id'	=> 1,
				'name' 			=> 'Ciputat',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			46 => array(
				'country_id'	=> 1,
				'name' 			=> 'Ciampea',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			47 => array(
				'country_id'	=> 1,
				'name' 			=> 'Sumedang Utara',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			48 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cileungsi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			49 => array(
				'country_id'	=> 1,
				'name' 			=> 'Rengasdengklok',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			50 => array(
				'country_id'	=> 1,
				'name' 			=> 'Parung',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			51 => array(
				'country_id'	=> 1,
				'name' 			=> 'Curug',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			52 => array(
				'country_id'	=> 1,
				'name' 			=> 'Labuhanbajo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			53 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cibinong',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			54 => array(
				'country_id'	=> 1,
				'name' 			=> 'Madiun',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			55 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pemalang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			56 => array(
				'country_id'	=> 1,
				'name' 			=> 'Lembang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			57 => array(
				'country_id'	=> 1,
				'name' 			=> 'Probolinggo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			58 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pamulang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			59 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cikupa',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			60 => array(
				'country_id'	=> 1,
				'name' 			=> 'Salatiga',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			61 => array(
				'country_id'	=> 1,
				'name' 			=> 'Plumbon',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			62 => array(
				'country_id'	=> 1,
				'name' 			=> 'Banjaran',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			63 => array(
				'country_id'	=> 1,
				'name' 			=> 'Serang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			64 => array(
				'country_id'	=> 1,
				'name' 			=> 'Lawang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			65 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pasuruan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			66 => array(
				'country_id'	=> 1,
				'name' 			=> 'Sunggal',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			67 => array(
				'country_id'	=> 1,
				'name' 			=> 'Perbaungan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			68 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pasarkemis',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			69 => array(
				'country_id'	=> 1,
				'name' 			=> 'Soreang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			70 => array(
				'country_id'	=> 1,
				'name' 			=> 'Purwodadi',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			71 => array(
				'country_id'	=> 1,
				'name' 			=> 'Metro',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			72 => array(
				'country_id'	=> 1,
				'name' 			=> 'Lubuklinggau',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			73 => array(
				'country_id'	=> 1,
				'name' 			=> 'Astanajapura',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			74 => array(
				'country_id'	=> 1,
				'name' 			=> 'Cikampek',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			75 => array(
				'country_id'	=> 1,
				'name' 			=> 'Gorontalo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			76 => array(
				'country_id'	=> 1,
				'name' 			=> 'Dumai',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			77 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tanjungbalai',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			78 => array(
				'country_id'	=> 1,
				'name' 			=> 'Sidoarjo',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			79 => array(
				'country_id'	=> 1,
				'name' 			=> 'Weru',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			80 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bitung',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			81 => array(
				'country_id'	=> 1,
				'name' 			=> 'Jayapura',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			82 => array(
				'country_id'	=> 1,
				'name' 			=> 'Baturaja',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			83 => array(
				'country_id'	=> 1,
				'name' 			=> 'Adiwerna',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			84 => array(
				'country_id'	=> 1,
				'name' 			=> 'Singaraja',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			85 => array(
				'country_id'	=> 1,
				'name' 			=> 'Blitar',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			86 => array(
				'country_id'	=> 1,
				'name' 			=> 'Martapura',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			87 => array(
				'country_id'	=> 1,
				'name' 			=> 'Kisaran',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			88 => array(
				'country_id'	=> 1,
				'name' 			=> 'Teluknaga',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			89 => array(
				'country_id'	=> 1,
				'name' 			=> 'Ungaran',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			90 => array(
				'country_id'	=> 1,
				'name' 			=> 'Rangkasbitung',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			91 => array(
				'country_id'	=> 1,
				'name' 			=> 'Klaten',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			92 => array(
				'country_id'	=> 1,
				'name' 			=> 'Jombang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			93 => array(
				'country_id'	=> 1,
				'name' 			=> 'Paseh',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			94 => array(
				'country_id'	=> 1,
				'name' 			=> 'Pangkalpinang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			95 => array(
				'country_id'	=> 1,
				'name' 			=> 'Sorong',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			96 => array(
				'country_id'	=> 1,
				'name' 			=> 'Tanjungpinang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			97 => array(
				'country_id'	=> 1,
				'name' 			=> 'Padalarang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			98 => array(
				'country_id'	=> 1,
				'name' 			=> 'Ciamis',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			99 => array(
				'country_id'	=> 1,
				'name' 			=> 'Lumajang',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			100 => array(
				'country_id'	=> 1,
				'name' 			=> 'Bangkalan',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
			101 => array(
				'country_id'	=> 1,
				'name' 			=> 'Batu',
				'status' 		=> 1,
				'created_at'	=> time(),
				'updated_at' 	=> time(),
			),
		);

		DB::table($table)->insert($data);
	}

}